version: '3.9'
services:
  app:
    build: .
    # build:
      # context: .
      # args:
        # DEPLOY_ENV: development
    # # command: sh -c "rm -f tmp/pid/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    command: /bin/sh
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    tty: true
    # user: 1000:1000
